# Site settings
title: Instant Tub Price | Professional Tub & Shower Remodeling
email: info@instanttubprice.com
description: >-
  Get instant pricing estimates for your tub and shower remodel project. Professional bathroom installation services with transparent pricing and exceptional quality. Serving homeowners nationwide with premium bathroom renovations.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://instanttubprice.com/" # the base hostname & protocol for your site
twitter_username: instanttubprice
github_username: instanttubprice

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO settings
lang: en_US
author: Instant Tub Price
social:
  name: Instant Tub Price
  links:
    - https://twitter.com/instanttubprice
    - https://www.facebook.com/instanttubprice
    - https://www.linkedin.com/company/instanttubprice

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
