# Site settings
title: Instant Bathroom Prices | Professional Tub & Shower Remodeling
email: info@instantbathroomprices.com
description: >-
  Get instant pricing estimates for your tub and shower remodel project. Professional bathroom installation services with transparent pricing and exceptional quality. Serving homeowners nationwide with premium bathroom renovations.
baseurl: "" # the subpath of your site, e.g. /blog
url: "instanttubprice.com" # the base hostname & protocol for your site
twitter_username: instantbathroom
github_username: instantbathroom

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO settings
lang: en_US
author: Instant Bathroom Prices
social:
  name: Instant Bathroom Prices
  links:
    - https://twitter.com/instantbathroom
    - https://www.facebook.com/instantbathroomprices
    - https://www.linkedin.com/company/instantbathroomprices

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

